### ISSUE TITLE
Post indexes

### ISSUE THREAD

**Issue by maaaks** [maaaks/andreas#1]
There are two main ways in which user interacts with a blog server while reading it:
1. user requests list of posts (by author, by date, by tag, ...), and server returns them;
2. user requests a single post (by URL), and server returns it.

I think it will be relatively easy to make some kind of signatures that will guarantee that certain author wrote/edited certain post (situation 2). Basically, it's like this: «I am the author, I signed it, and I meant this post to have this hash». Later, if someone finds a server showing the content not signed by author, we can automatically punish the server by lowering its rating.

But what about lists (situation 1)? When user asks server to show latest post by an author but server hides some of them, it still looks like bug (or censorship), even though every post returned by the server is signed. Can we do anything about it?

My idea would be: «I am the author, and from my side it looks like hash of the whole index is now this». But it's not perfect. First of all, this requires author's software to have _the entire index_ locally every time he publishes a new tweet, and that's a strange requirement. Second of all, to verify hash the reader also needs to get the whole index, not just the latest ten articles which he would normally see on the screen. Plus, there are a lot of other lists that won't be signed by the author, like «All posts with this tag». This makes any solution kind of useless: it won't work in general, only in some cases.

What do you think? How can we verify post indexes?

By the way, are there any hash functions so that `hash(a+b) = hash(a) + hash(b)` or something like that? I guess such function could help us here.

**Comment by maaaks** [comment]
Hmm. Let's recall what I wrote in [my old post on LOR](https://www.linux.org.ru/forum/talks/10615831). Without reading it all (it's writing is disgusting, I don't like to re-read it), it seems like my idea was not to verify anything but just to make cross-checking.

Looks like this: I ask Abc.net, what are 10 latest posts by Alice? It gives me 10 posts. I ask Xyz.net the same question, and it gives me 10 posts. If the results are different, I should suspect something. If, on the other hand, every site show me the same list, I should think «Hmm, whatever Alice wrote in reality, it doesn't matter, because the world now remembers her blog like this and no one ever saw other posts».

This is definitely not perfect solution, its just a workaround, a way to live in a world without a solution.

**Comment by maaaks** [comment]
Oh, here's another idea!

> I am the author, here's my brand new post «Boo!» with tags `Aaa`, `Bbb`, `Ccc`.
>
> By the way, previous post in the blog was #12345.
> Previous post under `Aaa` was #95.
> Previous post under `Bbb` was #545.
> Previous post under `Ccc` was #632.
> Call the police if your server skipped some of them.

**Comment by Plaque-fcc** [comment]
It's police who asked them to skip some.

On April 28, 2017 11:36:12 AM GMT+03:00, Max Alibaev <notifications@github.com> wrote:
>Oh, here's another idea!
>
>> I am the author, here's my brand new post «Boo!» with tags `Aaa`,
>`Bbb`, `Ccc`.
>>
>> By the way, previous post in the blog was #12345.
>> Previous post under `Aaa` was #95.
>> Previous post under `Bbb` was #545.
>> Previous post under `Ccc` was #632.
>> Call the police if your server skipped some of them.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maaaks/andreas/issues/1#issuecomment-297941400

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maaaks** [comment]
Please let's discuss it seriously.

The problem I see with my last post is that it's still a solution for a specific cases only: «all posts by author», «all posts by author+tag». If in tomorrow's world everyone will begin using geotags as main way of navigation, those indexes won't be verified.

**Comment by maaaks** [comment]
Okay, so let's stick with cross-checking but make a special protocol for exchanging them.

>> Hi, I am author and I am going to publish a post. With this post, I will have this hashes for most popular indexes on my site.
>
> Nice, and I am a server that will (hopefully) keep this hashes forever. If someone asks me for them, I will provide these hashes.

And later:

>>Hi author, it's the verification server again, I see that a lot of people are viewing your posts with the following query which is not covered by your hashes. Could you please sign your index for this query?
>
>Ok.

**Comment by Plaque-fcc** [comment]
Adding a layer for partial integrity checking sounds better to me; this opens a door for fake network trust poisoning, though.

**Comment by maaaks** [comment]
I don't understand (as always :smile:), please explain more when you'll can.

**Comment by maaaks** [comment]
If we choose my way (or, maybe, any other), we need to define a query language for specifying ppost indexes. Basically, we need to reinvent a strict, safe and very TIOWTDI-ish version of SQL.

**Comment by maaaks** [comment]
Won't do it.
